// app/components/Navigation.tsx
import { useState, useEffect, useRef } from 'react';
import { slides as allSlides, getSortedSlides } from './Work';

function shuffleArray<T>(array: T[]): T[] {
  const arr = array.slice();
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

export function Navigation() {
  // Core state
  const [hasMounted, setHasMounted] = useState(false);
  const [activeSection, setActiveSection] = useState(0);
  const [windowHeight, setWindowHeight] = useState(1080);
  const [mobileNavOpen, setMobileNavOpen] = useState(false);
  const [isNavigating, setIsNavigating] = useState(false);

  // Refs
  const slides = getSortedSlides();
  const mobileNavListRef = useRef<HTMLDivElement>(null);
  const activeBtnRef = useRef<HTMLButtonElement>(null);
  const autoSnapTimeoutRef = useRef<NodeJS.Timeout | undefined>(undefined);

  useEffect(() => {
    setHasMounted(true);
  }, []);

  useEffect(() => {
    setWindowHeight(window.innerHeight);
    const handleResize = () => setWindowHeight(window.innerHeight);
    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  // Centralized scroll logic
  const scrollToSection = (sectionIndex: number) => {
    const sectionId = slides[sectionIndex]?.id;
    if (sectionId) {
      const element = document.getElementById(sectionId);
      if (element) {
        // Add class for optimized text rendering during scroll
        document.documentElement.classList.add('smooth-scroll');

        element.scrollIntoView({
          behavior: 'smooth',
          block: 'start',
          inline: 'nearest',
        });
        setMobileNavOpen(false);

        // Remove class after scroll animation completes
        setTimeout(() => {
          document.documentElement.classList.remove('smooth-scroll');
        }, 800);
      }
    }
  };

  // Calculate current position within active section
  const getCurrentPosition = () => {
    const currentSection = document.getElementById(slides[activeSection]?.id);
    if (!currentSection)
      return { positionInSection: 0.5, isWellCentered: true };

    const scrollTop = window.pageYOffset || document.documentElement.scrollTop;
    const sectionTop = currentSection.offsetTop;
    const sectionHeight = currentSection.offsetHeight;
    const windowHeight = window.innerHeight;

    const positionInSection =
      (scrollTop - sectionTop) / (sectionHeight - windowHeight);
    const isWellCentered = positionInSection >= 0.1 && positionInSection <= 0.9;

    return { positionInSection, isWellCentered };
  };

  // Track active section and handle auto-snap
  useEffect(() => {
    const handleScroll = () => {
      if (isNavigating) return;

      // Update active section
      const sections = document.querySelectorAll('[id^="section-"]');
      const scrollPosition = window.scrollY;

      if (scrollPosition < windowHeight / 3) {
        setActiveSection(0);
      } else {
        let currentSection = 0;
        sections.forEach((section) => {
          const element = section as HTMLElement;
          const offsetTop = element.offsetTop;
          const offsetHeight = element.offsetHeight;
          if (
            scrollPosition + windowHeight / 2 >= offsetTop &&
            scrollPosition + windowHeight / 2 < offsetTop + offsetHeight
          ) {
            const idx = slides.findIndex((s) => s.id === element.id);
            if (idx !== -1) {
              currentSection = idx;
            }
          }
        });
        setActiveSection(currentSection);
      }

      // Auto-snap logic
      if (autoSnapTimeoutRef.current) {
        clearTimeout(autoSnapTimeoutRef.current);
      }

      autoSnapTimeoutRef.current = setTimeout(() => {
        const { isWellCentered } = getCurrentPosition();
        if (!isWellCentered && !isNavigating) {
          setIsNavigating(true);
          scrollToSection(activeSection);
          setTimeout(() => setIsNavigating(false), 300);
        }
      }, 150);
    };

    window.addEventListener('scroll', handleScroll);
    handleScroll();

    return () => {
      window.removeEventListener('scroll', handleScroll);
      if (autoSnapTimeoutRef.current) {
        clearTimeout(autoSnapTimeoutRef.current);
      }
    };
  }, [windowHeight, slides, activeSection, isNavigating]);

  // Navigation event handlers
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'ArrowDown' || e.key === 'ArrowUp') {
        e.preventDefault();

        if (isNavigating) return;

        let targetSection = activeSection;
        if (e.key === 'ArrowDown' && activeSection < slides.length - 1) {
          targetSection = activeSection + 1;
        } else if (e.key === 'ArrowUp' && activeSection > 0) {
          targetSection = activeSection - 1;
        }

        if (targetSection !== activeSection) {
          setIsNavigating(true);

          // Clear any pending auto-snap timeout
          if (autoSnapTimeoutRef.current) {
            clearTimeout(autoSnapTimeoutRef.current);
            autoSnapTimeoutRef.current = undefined;
          }

          scrollToSection(targetSection);
          setTimeout(() => setIsNavigating(false), 500);
        }
      }
    };

    const handleWheel = (e: WheelEvent) => {
      if (isNavigating) return;

      const { positionInSection } = getCurrentPosition();
      const scrollStrength = Math.abs(e.deltaY);
      const isNearEdge = positionInSection < 0.1 || positionInSection > 0.9;
      const isBetweenSlides =
        positionInSection < -0.05 || positionInSection > 1.05;

      if (scrollStrength > 15 && (isNearEdge || isBetweenSlides)) {
        let targetSection = activeSection;

        if (e.deltaY > 0 && activeSection < slides.length - 1) {
          targetSection = activeSection + 1;
        } else if (e.deltaY < 0 && activeSection > 0) {
          targetSection = activeSection - 1;
        }

        if (targetSection !== activeSection) {
          e.preventDefault();
          setIsNavigating(true);

          // Clear any pending auto-snap timeout to prevent conflicts
          if (autoSnapTimeoutRef.current) {
            clearTimeout(autoSnapTimeoutRef.current);
            autoSnapTimeoutRef.current = undefined;
          }

          scrollToSection(targetSection);

          // Longer timeout to prevent double-triggering
          setTimeout(() => setIsNavigating(false), 500);
        }
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    window.addEventListener('wheel', handleWheel, { passive: false });

    return () => {
      window.removeEventListener('keydown', handleKeyDown);
      window.removeEventListener('wheel', handleWheel);
    };
  }, [activeSection, slides.length, isNavigating]);

  // Mobile navigation scroll effect
  useEffect(() => {
    if (mobileNavOpen && activeBtnRef.current && mobileNavListRef.current) {
      activeBtnRef.current.scrollIntoView({
        block: 'center',
        behavior: 'auto',
      });
    }
  }, [mobileNavOpen, activeSection]);

  // Only render after mount
  if (!hasMounted) return null;

  // Navigation numbers
  const totalSections = slides.length;
  const getVisibleNumbers = () => {
    const availableHeight = windowHeight - 128;
    const numberHeight = 32;
    const maxVisible = Math.floor(availableHeight / numberHeight);
    const halfRange = Math.floor(maxVisible / 2);
    let start = Math.max(0, activeSection - halfRange);
    let end = Math.min(totalSections - 1, start + maxVisible - 1);
    if (end === totalSections - 1) {
      start = Math.max(0, totalSections - maxVisible);
    }
    const visibleNumbers = [];
    for (let i = start; i <= end; i++) {
      visibleNumbers.push(i);
    }
    return visibleNumbers;
  };
  const visibleNumbers = getVisibleNumbers();

  // Shuffle handler
  const handleShuffle = () => {
    if (slides.length <= 1) return;
    const randomIdx = Math.floor(Math.random() * (slides.length - 1)) + 1;
    scrollToSection(randomIdx);
  };

  return (
    <>
      {/* Mobile Toggle Button */}
      <button
        onClick={() => setMobileNavOpen(!mobileNavOpen)}
        className="fixed top-6 left-6 z-50 p-2 transition-all duration-300 rounded xl:hidden"
        style={{
          backgroundColor: mobileNavOpen ? 'var(--ivory-med)' : 'transparent',
          color: 'var(--text-color)',
        }}
        onMouseEnter={(e) => {
          e.currentTarget.style.backgroundColor = 'var(--ivory-med)';
        }}
        onMouseLeave={(e) => {
          e.currentTarget.style.backgroundColor = mobileNavOpen
            ? 'var(--ivory-med)'
            : 'transparent';
        }}
        aria-label="Toggle navigation"
      >
        {mobileNavOpen ? (
          <svg
            width="28"
            height="28"
            viewBox="0 0 28 28"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
            className="block mx-auto my-auto"
          >
            <line
              x1="7"
              y1="7"
              x2="21"
              y2="21"
              stroke="var(--dark-gray)"
              strokeWidth="1.2"
              strokeLinecap="round"
            />
            <line
              x1="21"
              y1="7"
              x2="7"
              y2="21"
              stroke="var(--dark-gray)"
              strokeWidth="1.2"
              strokeLinecap="round"
            />
          </svg>
        ) : (
          <svg
            width="28"
            height="28"
            viewBox="0 0 28 28"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
            className="block mx-auto my-auto"
          >
            <line
              x1="6"
              y1="9"
              x2="22"
              y2="9"
              stroke="var(--dark-gray)"
              strokeWidth="1.2"
              strokeLinecap="round"
            />
            <line
              x1="6"
              y1="14"
              x2="22"
              y2="14"
              stroke="var(--dark-gray)"
              strokeWidth="1.2"
              strokeLinecap="round"
            />
            <line
              x1="6"
              y1="19"
              x2="22"
              y2="19"
              stroke="var(--dark-gray)"
              strokeWidth="1.2"
              strokeLinecap="round"
            />
          </svg>
        )}
      </button>

      {/* Desktop Navigation */}
      <nav
        className="fixed left-0 z-50 h-screen w-12 hidden xl:flex flex-col items-stretch backdrop-blur-md pointer-events-auto"
        style={{
          backgroundColor: 'rgba(240, 238, 230, 0.6)', // --ivory-med with transparency
        }}
      >
        <div className="flex flex-col justify-evenly h-full py-4 w-full items-center bg-transparent flex-1">
          {visibleNumbers.map((visibleIdx) => {
            const slide = slides[visibleIdx];
            const sectionNumber = String(visibleIdx).padStart(2, '0');
            const isActive = activeSection === visibleIdx;
            return (
              <button
                key={slide?.id || visibleIdx}
                onClick={() => scrollToSection(visibleIdx)}
                className="text-xs tracking-widest transition-all duration-300 text-left py-1"
                style={{
                  color: isActive ? 'var(--slate)' : 'var(--gray)',
                  fontWeight: isActive ? 'bold' : '300',
                  transform: isActive ? 'scale(1.1)' : 'scale(1)',
                }}
                onMouseEnter={(e) => {
                  e.currentTarget.style.color = 'var(--slate)';
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.color = isActive
                    ? 'var(--slate)'
                    : 'var(--gray)';
                }}
                tabIndex={0}
                aria-label={`Go to section ${sectionNumber}`}
                ref={isActive ? activeBtnRef : undefined}
              >
                {sectionNumber}
              </button>
            );
          })}
        </div>
        {/* Shuffle button */}
        <div className="flex justify-center w-full pb-2">
          <button
            onClick={handleShuffle}
            aria-label="Shuffle to random slide"
            className="w-8 h-8 flex items-center justify-center rounded transition-colors focus:outline-none focus:ring-2"
            style={{
              color: 'var(--gray)',
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.color = 'var(--slate)';
              e.currentTarget.style.backgroundColor = 'var(--ivory-dark)';
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.color = 'var(--gray)';
              e.currentTarget.style.backgroundColor = 'transparent';
            }}
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="21"
              height="21"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              aria-hidden="true"
            >
              <polyline points="16 3 21 3 21 8" />
              <line x1="4" y1="20" x2="21" y2="3" />
              <polyline points="21 16 21 21 16 21" />
              <line x1="15" y1="15" x2="21" y2="21" />
              <line x1="4" y1="4" x2="9" y2="9" />
            </svg>
          </button>
        </div>
      </nav>

      {/* Mobile Navigation Overlay */}
      {mobileNavOpen && (
        <div className="fixed inset-0 z-40 xl:hidden flex flex-col">
          {/* Backdrop */}
          <div
            className="absolute inset-0 backdrop-blur-[1px]"
            style={{
              backgroundColor: 'rgba(0, 0, 0, 0.05)',
            }}
            onClick={() => setMobileNavOpen(false)}
          ></div>

          {/* Navigation Panel */}
          <div
            className="relative h-full w-24 shadow-2xl flex flex-col"
            style={{
              backgroundColor: 'var(--background-color)',
              borderRight: '1px solid var(--ivory-dark)',
            }}
          >
            <div className="flex flex-col h-full py-20 px-2">
              <div className="flex-1 overflow-y-auto" ref={mobileNavListRef}>
                <div className="flex flex-col space-y-2">
                  {Array.from({ length: totalSections }, (_, index) => {
                    const isActive = activeSection === index;
                    return (
                      <button
                        key={index}
                        ref={isActive ? activeBtnRef : undefined}
                        onClick={() => scrollToSection(index)}
                        className="text-xs tracking-widest transition-all duration-300 text-center py-2 rounded"
                        style={{
                          color: isActive ? 'var(--slate)' : 'var(--gray)',
                          fontWeight: isActive ? 'bold' : '300',
                          backgroundColor: isActive
                            ? 'var(--ivory-med)'
                            : 'transparent',
                        }}
                        onMouseEnter={(e) => {
                          e.currentTarget.style.color = 'var(--slate)';
                        }}
                        onMouseLeave={(e) => {
                          e.currentTarget.style.color = isActive
                            ? 'var(--slate)'
                            : 'var(--gray)';
                        }}
                      >
                        {String(index).padStart(2, '0')}
                      </button>
                    );
                  })}
                </div>
              </div>
              {/* Shuffle button for mobile */}
              <div className="flex justify-center w-full pb-2">
                <button
                  onClick={handleShuffle}
                  aria-label="Shuffle to random slide"
                  className="w-8 h-8 mt-4 mr-2 flex items-center justify-center rounded transition-colors focus:outline-none focus:ring-2"
                  style={{
                    color: 'var(--gray)',
                  }}
                  onMouseEnter={(e) => {
                    e.currentTarget.style.color = 'var(--slate)';
                    e.currentTarget.style.backgroundColor = 'var(--ivory-dark)';
                  }}
                  onMouseLeave={(e) => {
                    e.currentTarget.style.color = 'var(--gray)';
                    e.currentTarget.style.backgroundColor = 'transparent';
                  }}
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="21"
                    height="21"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    aria-hidden="true"
                  >
                    <polyline points="16 3 21 3 21 8" />
                    <line x1="4" y1="20" x2="21" y2="3" />
                    <polyline points="21 16 21 21 16 21" />
                    <line x1="15" y1="15" x2="21" y2="21" />
                    <line x1="4" y1="4" x2="9" y2="9" />
                  </svg>
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </>
  );
}

// src/lib/components/Navigation.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { getSortedSlides } from '$lib/data';
  import { activeSection, mobileNavOpen, isNavigating, windowHeight } from '$lib/stores';

  const slides = getSortedSlides();
  let hasMounted = false;
  let lastNavigationTime = 0;
  
  // Touch state
  let touchStartY: number | null = null;
  let touchEndY: number | null = null;

  let mobileNavListRef: HTMLDivElement;
  let activeBtnRef: HTMLButtonElement;

  onMount(() => {
    hasMounted = true;
    // Initialize slide positions
    // We need to wait for DOM to update
    requestAnimationFrame(() => {
        const sections = document.querySelectorAll('[id^="section-"]');
        sections.forEach((section) => {
            const element = section as HTMLElement;
            if (element.id === 'section-00') {
                element.style.opacity = '1';
                element.style.zIndex = '10';
                element.style.transition = 'opacity 0.4s ease-in';
            } else {
                element.style.opacity = '0';
                element.style.zIndex = '1';
                element.style.transition = 'opacity 0.3s ease-out';
            }
        });
        activeSection.set(-1);
    });

    // Resize listener
    const handleResize = () => windowHeight.set(window.innerHeight);
    window.addEventListener('resize', handleResize);
    windowHeight.set(window.innerHeight);

    // Touch listeners
    window.addEventListener('touchstart', handleTouchStart, { passive: true });
    window.addEventListener('touchmove', handleTouchMove, { passive: true });
    window.addEventListener('touchend', handleTouchEnd);

    // Keyboard and Wheel
    window.addEventListener('keydown', handleKeyDown);
    window.addEventListener('wheel', handleWheel, { passive: false });

    return () => {
      window.removeEventListener('resize', handleResize);
      window.removeEventListener('touchstart', handleTouchStart);
      window.removeEventListener('touchmove', handleTouchMove);
      window.removeEventListener('touchend', handleTouchEnd);
      window.removeEventListener('keydown', handleKeyDown);
      window.removeEventListener('wheel', handleWheel);
    };
  });

  // Logic for scrolling
  function scrollToSection(sectionIndex: number, closeMobileMenu = false) {
    activeSection.set(sectionIndex);

    const sections = document.querySelectorAll('[id^="section-"]');
    const currentActive = document.querySelector('section[style*="opacity: 1"]') as HTMLElement;
    
    let targetSection: HTMLElement;
    if (sectionIndex === -1) {
      targetSection = document.getElementById('section-00') as HTMLElement;
    } else {
      const slide = slides[sectionIndex];
      if (slide) {
        targetSection = document.getElementById(slide.id) as HTMLElement;
      } else {
          return;
      }
    }
    
    if (!targetSection) return;

    if (currentActive && currentActive !== targetSection) {
      currentActive.style.transition = 'opacity 0.3s ease-out';
      currentActive.style.opacity = '0';
      currentActive.style.zIndex = '1';
      
      setTimeout(() => {
        targetSection.style.transition = 'opacity 0.4s ease-in';
        targetSection.style.opacity = '1';
        targetSection.style.zIndex = '10';
      }, 300);
    } else {
      targetSection.style.transition = 'opacity 0.4s ease-in';
      targetSection.style.opacity = '1';
      targetSection.style.zIndex = '10';
    }

    sections.forEach((section) => {
      const element = section as HTMLElement;
      if (element !== targetSection && element !== currentActive) {
        element.style.opacity = '0';
        element.style.zIndex = '1';
      }
    });

    if (closeMobileMenu) mobileNavOpen.set(false);
  }

  // Event Handlers
  const handleTouchStart = (e: TouchEvent) => {
      touchStartY = e.touches[0].clientY;
  };

  const handleTouchMove = (e: TouchEvent) => {
      touchEndY = e.touches[0].clientY;
  };

  const handleTouchEnd = () => {
      if (touchStartY === null || touchEndY === null) return;

      const currentTime = Date.now();
      if ($isNavigating || currentTime - lastNavigationTime < 150) {
        touchStartY = null;
        touchEndY = null;
        return;
      }

      const deltaY = touchStartY - touchEndY;
      const minSwipeDistance = 50;

      if (Math.abs(deltaY) < minSwipeDistance) {
        touchStartY = null;
        touchEndY = null;
        return;
      }

      let target = $activeSection;
      if (deltaY > 0) { // Swiped up -> next
        if ($activeSection === -1) target = 0;
        else if ($activeSection < slides.length - 1) target = $activeSection + 1;
      } else { // Swiped down -> prev
        if ($activeSection === 0) target = -1;
        else if ($activeSection > 0) target = $activeSection - 1;
      }

      if (target !== $activeSection) {
        lastNavigationTime = currentTime;
        isNavigating.set(true);
        scrollToSection(target);
        setTimeout(() => isNavigating.set(false), 600);
      }
      touchStartY = null;
      touchEndY = null;
  };

  const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'ArrowDown' || e.key === 'ArrowUp') {
        e.preventDefault();
        const currentTime = Date.now();
        if ($isNavigating || currentTime - lastNavigationTime < 150) return;

        let target = $activeSection;
        if (e.key === 'ArrowDown') {
          if ($activeSection === -1) target = 0;
          else if ($activeSection < slides.length - 1) target = $activeSection + 1;
        } else if (e.key === 'ArrowUp') {
            if ($activeSection === 0) target = -1;
            else if ($activeSection > 0) target = $activeSection - 1;
        }

        if (target !== $activeSection) {
            lastNavigationTime = currentTime;
            isNavigating.set(true);
            scrollToSection(target);
            setTimeout(() => isNavigating.set(false), 600);
        }
      }
  };

  const handleWheel = (e: WheelEvent) => {
      e.preventDefault();
      const currentTime = Date.now();
      if ($isNavigating || currentTime - lastNavigationTime < 150) return;

      const scrollStrength = Math.abs(e.deltaY);
      if (scrollStrength < 15) return;

      let target = $activeSection;
      if (e.deltaY > 0) {
          if ($activeSection === -1) target = 0;
          else if ($activeSection < slides.length - 1) target = $activeSection + 1;
      } else if (e.deltaY < 0) {
          if ($activeSection === 0) target = -1;
          else if ($activeSection > 0) target = $activeSection - 1;
      }

      if (target !== $activeSection) {
          lastNavigationTime = currentTime;
          isNavigating.set(true);
          scrollToSection(target);
          setTimeout(() => isNavigating.set(false), 600);
      }
  };

  function handleShuffle() {
    if (slides.length <= 1) return;
    const randomIdx = Math.floor(Math.random() * (slides.length - 1)) + 1;
    scrollToSection(randomIdx);
  }

  // Visible numbers calculation
  $: totalSections = slides.length;
  $: availableHeight = $windowHeight - 128;
  $: numberHeight = 32;
  $: maxVisible = Math.floor(availableHeight / numberHeight);
  $: halfRange = Math.floor(maxVisible / 2);
  $: start = Math.max(0, $activeSection - halfRange);
  $: end = Math.min(totalSections - 1, start + maxVisible - 1);
  // Correction if end is capped
  $: adjustedStart = (end === totalSections - 1) ? Math.max(0, totalSections - maxVisible) : start;
  
  $: visibleNumbers = (() => {
      const nums = [];
      if (adjustedStart === 0) nums.push(-1);
      for (let i = Math.max(1, adjustedStart); i <= end; i++) {
          nums.push(i);
      }
      return nums;
  })();

  // Scroll mobile nav into view
  $: if ($mobileNavOpen && activeBtnRef && mobileNavListRef) {
      activeBtnRef.scrollIntoView({ block: 'center', behavior: 'auto' });
  }
</script>

{#if hasMounted}
  <!-- Mobile Toggle Button -->
  <button
    on:click={() => mobileNavOpen.set(!$mobileNavOpen)}
    on:mouseenter={(e) => e.currentTarget.style.backgroundColor = 'var(--ivory-med)'}
    on:mouseleave={(e) => e.currentTarget.style.backgroundColor = $mobileNavOpen ? 'var(--ivory-med)' : 'transparent'}
    class="fixed top-6 left-6 z-50 p-2 transition-all duration-300 rounded xl:hidden"
    style="background-color: {$mobileNavOpen ? 'var(--ivory-med)' : 'transparent'}; color: var(--text-color);"
    aria-label="Toggle navigation"
  >
    {#if $mobileNavOpen}
      <svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg" class="block mx-auto my-auto">
        <line x1="7" y1="7" x2="21" y2="21" stroke="var(--dark-gray)" stroke-width="1.2" stroke-linecap="round" />
        <line x1="21" y1="7" x2="7" y2="21" stroke="var(--dark-gray)" stroke-width="1.2" stroke-linecap="round" />
      </svg>
    {:else}
      <svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg" class="block mx-auto my-auto">
        <line x1="6" y1="9" x2="22" y2="9" stroke="var(--dark-gray)" stroke-width="1.2" stroke-linecap="round" />
        <line x1="6" y1="14" x2="22" y2="14" stroke="var(--dark-gray)" stroke-width="1.2" stroke-linecap="round" />
        <line x1="6" y1="19" x2="22" y2="19" stroke="var(--dark-gray)" stroke-width="1.2" stroke-linecap="round" />
      </svg>
    {/if}
  </button>

  <!-- Desktop Navigation -->
  <nav
    class="fixed left-0 z-50 h-screen w-12 hidden xl:flex flex-col items-stretch backdrop-blur-md pointer-events-auto"
    style="background-color: var(--nav-bg);"
  >
    <div class="flex flex-col justify-evenly h-full py-4 w-full items-center bg-transparent flex-1">
      {#each visibleNumbers as visibleIdx}
        {@const isHeroSlide = visibleIdx === -1}
        {@const sectionNumber = isHeroSlide ? '00' : String(visibleIdx).padStart(2, '0')}
        {@const isActive = isHeroSlide ? ($activeSection === -1) : ($activeSection === visibleIdx)}
        {@const targetSection = isHeroSlide ? -1 : visibleIdx}
        
        <button
          on:click={() => scrollToSection(targetSection, false)}
          on:mouseenter={(e) => e.currentTarget.style.color = 'var(--slate)'}
          on:mouseleave={(e) => e.currentTarget.style.color = isActive ? 'var(--slate)' : 'var(--gray)'}
          class="text-xs tracking-widest transition-all duration-300 text-left py-1"
          style="color: {isActive ? 'var(--slate)' : 'var(--gray)'}; font-weight: {isActive ? 'bold' : '300'}; transform: {isActive ? 'scale(1.1)' : 'scale(1)'};"
          aria-label="Go to section {sectionNumber}"
        >
          {sectionNumber}
        </button>
      {/each}
    </div>
    
    <!-- Shuffle button -->
    <div class="flex justify-center w-full pb-2">
      <button
        on:click={handleShuffle}
        on:mouseenter={(e) => {
          e.currentTarget.style.color = 'var(--slate)';
          e.currentTarget.style.backgroundColor = 'var(--nav-hover-bg)';
        }}
        on:mouseleave={(e) => {
          e.currentTarget.style.color = 'var(--gray)';
          e.currentTarget.style.backgroundColor = 'transparent';
        }}
        aria-label="Shuffle to random slide"
        class="w-8 h-8 flex items-center justify-center rounded transition-colors focus:outline-none focus:ring-2"
        style="color: var(--gray);"
      >
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 17 17" fill="none" stroke="currentColor" stroke-width="0" aria-hidden="true">
          <path d="M8.94 6.871l1.081-1.34-0.004-0.003c0.855-0.971 2.087-1.528 3.378-1.528h1.898l-1.646-1.646 0.707-0.707 2.853 2.853-2.854 2.854-0.707-0.707 1.647-1.647h-1.898c-0.989 0-1.931 0.425-2.595 1.159l-1.080 1.339-0.78-0.627zM5.851 10.696l-0.011-0.008c-0.667 0.833-1.663 1.312-2.733 1.312h-3.107v1h3.107c1.369 0 2.645-0.611 3.503-1.676l0.011 0.009 0.941-1.166-0.777-0.629-0.934 1.158zM13.646 10.354l1.647 1.646h-1.898c-1.052 0-2.031-0.469-2.7-1.281l-4.269-5.265-0.010 0.008c-0.85-0.926-2.048-1.462-3.309-1.462h-3.107v1h3.107c0.998 0 1.948 0.428 2.611 1.17l4.161 5.132-0.005 0.004c0.86 1.076 2.143 1.694 3.52 1.694h1.898l-1.646 1.646 0.707 0.707 2.854-2.854-2.854-2.854-0.707 0.709z" fill="currentColor" />
        </svg>
      </button>
    </div>
  </nav>

  <!-- Mobile Navigation Overlay -->
  {#if $mobileNavOpen}
    <div class="fixed inset-0 z-40 xl:hidden flex flex-col">
      <!-- Backdrop -->
      <div
        class="absolute inset-0 backdrop-blur-[1px]"
        style="background-color: rgba(0, 0, 0, 0.05);"
        on:click={() => mobileNavOpen.set(false)}
        role="button"
        tabindex="0"
        on:keydown={() => {}}
      ></div>

      <!-- Navigation Panel -->
      <div
        class="relative h-full w-24 shadow-2xl flex flex-col"
        style="background-color: var(--background-color); border-right: 1px solid var(--ivory-dark);"
      >
        <div class="flex flex-col h-full pt-20 pb-4 px-2">
          <div class="flex-1 overflow-y-auto flex items-center" bind:this={mobileNavListRef}>
            <div class="flex flex-col justify-evenly h-full w-full">
              <!-- Hero slide (00) -->
              <button
                bind:this={activeBtnRef}
                on:click={() => scrollToSection(-1, true)}
                on:mouseenter={(e) => e.currentTarget.style.color = 'var(--slate)'}
                on:mouseleave={(e) => e.currentTarget.style.color = $activeSection === -1 ? 'var(--slate)' : 'var(--gray)'}
                class="text-sm tracking-widest transition-all duration-300 text-center py-2 rounded"
                style="color: {$activeSection === -1 ? 'var(--slate)' : 'var(--gray)'}; font-weight: {$activeSection === -1 ? 'bold' : '300'}; background-color: {$activeSection === -1 ? 'var(--ivory-med)' : 'transparent'};"
              >
                00
              </button>
              
              <!-- Work slides -->
              {#each {length: slides.length} as _, index}
                {@const isActive = $activeSection === index}
                <!-- Only bind ref if it's the active one. Svelte logic is a bit tricky here in a loop. 
                     We can just conditionally bind if we used a component, but on native element it's harder.
                     We'll skip binding inside loop for now and trust that if activeSection changed, we find it?
                     Actually, we can use `use:action` or just rely on logic. 
                     The React code used a ref to scroll into view. 
                     We can just querySelector the active one in the effect.
                -->
                <button
                  on:click={() => scrollToSection(index, true)}
                  on:mouseenter={(e) => e.currentTarget.style.color = 'var(--slate)'}
                  on:mouseleave={(e) => e.currentTarget.style.color = isActive ? 'var(--slate)' : 'var(--gray)'}
                  class="text-sm tracking-widest transition-all duration-300 text-center py-2 rounded"
                  style="color: {isActive ? 'var(--slate)' : 'var(--gray)'}; font-weight: {isActive ? 'bold' : '300'}; background-color: {isActive ? 'var(--ivory-med)' : 'transparent'};"
                  data-active={isActive}
                >
                  {String(index).padStart(2, '0')}
                </button>
              {/each}
            </div>
          </div>
          
          <!-- Shuffle button for mobile -->
          <div class="flex justify-center w-full pb-2">
            <button
              on:click={handleShuffle}
              on:mouseenter={(e) => {
                e.currentTarget.style.color = 'var(--slate)';
                e.currentTarget.style.backgroundColor = 'var(--nav-hover-bg)';
              }}
              on:mouseleave={(e) => {
                e.currentTarget.style.color = 'var(--gray)';
                e.currentTarget.style.backgroundColor = 'transparent';
              }}
              aria-label="Shuffle to random slide"
              class="w-8 h-8 mt-4 mr-2 flex items-center justify-center rounded transition-colors focus:outline-none focus:ring-2"
              style="color: var(--gray);"
            >
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 17 17" fill="none" stroke="currentColor" stroke-width="0" aria-hidden="true">
                <path d="M8.94 6.871l1.081-1.34-0.004-0.003c0.855-0.971 2.087-1.528 3.378-1.528h1.898l-1.646-1.646 0.707-0.707 2.853 2.853-2.854 2.854-0.707-0.707 1.647-1.647h-1.898c-0.989 0-1.931 0.425-2.595 1.159l-1.080 1.339-0.78-0.627zM5.851 10.696l-0.011-0.008c-0.667 0.833-1.663 1.312-2.733 1.312h-3.107v1h3.107c1.369 0 2.645-0.611 3.503-1.676l0.011 0.009 0.941-1.166-0.777-0.629-0.934 1.158zM13.646 10.354l1.647 1.646h-1.898c-1.052 0-2.031-0.469-2.7-1.281l-4.269-5.265-0.010 0.008c-0.85-0.926-2.048-1.462-3.309-1.462h-3.107v1h3.107c0.998 0 1.948 0.428 2.611 1.17l4.161 5.132-0.005 0.004c0.86 1.076 2.143 1.694 3.52 1.694h1.898l-1.646 1.646 0.707 0.707 2.854-2.854-2.854-2.854-0.707 0.709z" fill="currentColor" />
              </svg>
            </button>
          </div>
        </div>
      </div>
    </div>
  {/if}
{/if}
